/** Declaration file generated by dts-gen */

// export = snarkjs;
declare module 'snarkjs' {
  declare const groth16: {
    exportSolidityCallData: any;
    fullProve: any;
    prove: any;
    verify: any;
  };
  declare const plonk: {
    exportSolidityCallData: any;
    fullProve: any;
    prove: any;
    setup: any;
    verify: any;
  };
  declare const powersOfTau: {
    beacon: any;
    challengeContribute: any;
    contribute: any;
    convert: any;
    exportChallenge: any;
    exportJson: any;
    importResponse: any;
    newAccumulator: any;
    preparePhase2: any;
    truncate: any;
    verify: any;
  };
  declare const r1cs: {
    exportJson: any;
    info: any;
    print: any;
  };
  declare const wtns: {
    calculate: any;
    debug: any;
    exportJson: any;
  };
  declare const zKey: {
    beacon: any;
    bellmanContribute: any;
    contribute: any;
    exportBellman: any;
    exportJson: any;
    exportSolidityVerifier: any;
    exportVerificationKey: any;
    importBellman: any;
    newZKey: any;
    verifyFromInit: any;
    verifyFromR1cs: any;
  };
};

