[package]
authors = ["tomo@noxx.xyz"]
compiler_version = "0.10.5"
name = "main"
type = "bin"

[dependencies]
noir_merkleroot = { tag = "v0.1.1", git = "https://github.com/tomoima525/noir-merkle-root" }